plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://hypothesizing-machine.github.io
baseurl: /oaio

title: Hypothesizing Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Hypothesizing-Machine
  verb: Hypothesizing
  instructions_file: hypothesizing.md
  token: openai
  server: https://localhost:443
  apiUrl: https://api.openai.com/v1/responses

app:
  worker_name: oaioapi.js

lm:
  model: gpt-5.1
  max_output_tokens: 100000
  reasoning_effort: high
  reasoning_summary: detailed
  temperature: 1.0

github_settings:
  owner: hypothesizing-machine
  repo: hypothesizing_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
